name: sync2gitee
on:
  push:
    branches: [ main ]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/<your-gitee-username>'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}
